# Generated by Django 2.1.7 on 2019-04-03 11:16

import agir.people.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0052_auto_20190313_1842")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="subscribed_sms",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Vous recevrez des sms de la France insoumise comme des meeting près de chez vous ou des appels à volontaire...",
                verbose_name="Recevoir les sms d'information",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="contact_phone",
            field=agir.people.model_fields.ValidatedPhoneNumberField(
                blank=True,
                max_length=128,
                unverified_value="U",
                validated_field_name="contact_phone_status",
                verbose_name="Numéro de contact",
            ),
        ),
    ]
