# Generated by Django 2.1.7 on 2019-04-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0053_auto_20190403_1316"),
        ("people", "0053_auto_20190402_1140"),
    ]

    operations = []
