# Generated by Django 2.2 on 2019-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0073_event_participation_template")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="dont_reference",
            field=models.BooleanField(
                default=False,
                verbose_name="Ne pas référencer l'événement dans les outils interne ainsi que dans les moteurs de recherches.",
            ),
        )
    ]
